version: '3.8'
services:
  mlflowdatabase:
    image: postgres:13.2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mlflow-postgres
      - POSTGRES_PASSWORD=mlflow-postgres
      - POSTGRES_DB=mlflow
    networks:
      - elastic    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - elastic
    depends_on: 
      - mlflowdatabase
  mlflowserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- mlflow-data:/opt/mlflow
      - /opt/mlflow:/opt/mlflow
    ports:
      - 5000:5000
    depends_on:
      - mlflowdatabase
    networks:
      - elastic
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
  db-data:
    driver: local
  mlflow-data:
    driver: local
networks:
  elastic:
    driver: bridge